pub mod completions;
pub mod github;
pub mod install;
pub mod paths;
pub mod rollback;
pub mod update;

pub use install::{install_binary, uninstall_binary};
pub use paths::detect_install_paths;
pub use update::{
    check_for_updates, check_for_updates_silent, check_for_updates_with_settings, perform_update,
};

/// embedded man page content (generated by `cargo run --bin generate-man`)
pub const MAN_PAGE: &[u8] = include_bytes!("../../man/cwm.1");

/// default man page installation directory
pub const MAN_DIR: &str = "/usr/local/share/man/man1";
